"use client";

import { Download } from "lucide-react";
import { Button } from "../ui/button";

export default function DownloadSummaryButton({
  title,
  originalFileUrl,
  summaryText,
  createdAt,
  fileName,
}: {
  title: string;
  originalFileUrl: string;
  summaryText: string;
  createdAt: string;
  fileName: string;
}) {
  const handleDownlaod = () => {
    const summaryContent = `# ${title} 
Generated Summary
Generated on : ${new Date(createdAt).toLocaleDateString()}
    
${summaryText}
    
Original File : ${fileName}
Generated by Summarize`;

    const blob = new Blob([summaryContent], { type: "text/plain" });
    console.log(blob);
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-z0-9]/gi, "_")}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <Button
      size="sm"
      className="h-8 px-3 bg-rose-100 text-rose-600 hover:text-rose-700 hover:bg-rose-50"
      onClick={handleDownlaod}
    >
      <Download className="h-4 w-4 mr-1" />
      Download Summary
    </Button>
  );
}
